# Generated by Django 4.2.5 on 2023-09-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriçao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos')),
                ('nome', models.CharField(max_length=250)),
                ('idade', models.IntegerField()),
                ('cpf', models.CharField(max_length=11)),
                ('endereço', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=200)),
                ('contatos', models.CharField(max_length=11)),
            ],
        ),
        migrations.DeleteModel(
            name='vagalumes',
        ),
    ]
